name: CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: |
          git submodule update --init --recursive
          nuget restore "ConfuserEx Dynamic Unpacker.sln"
          msbuild "ConfuserEx Dynamic Unpacker.sln" /p:Configuration=Release /m /verbosity:normal /p:WarningLevel=0
      - name: Create ZIP
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          Compress-Archive -Path Release/* -DestinationPath ConfuserExDyn

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ConfuserExDyn.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
